---

- name: Macbook Setup
  hosts: local

  tasks:

  - name: Tap caskroom/versions for edge versions
    homebrew_tap:
      name: homebrew/cask-versions

  - name: Install dev utilities
    homebrew: name={{ item }}
    with_items:
      - vim
      - git
      - fzf
      - the_silver_searcher
      - zsh
      - z
      - dnsmasq

  - name: Install common software
    homebrew_cask: name={{ item }}
    with_items:
      - google-chrome
      - firefox
      - slack
      - iterm2
      - sublime-text
      - alfred
      - docker-edge

  - name: Install oh-my-zsh
    shell: curl -L http://install.ohmyz.sh | sh creates=~/.oh-my-zsh

  - name: Initialize z on shell init
    lineinfile: dest=~/.zshrc line=". `brew --prefix`/etc/profile.d/z.sh"

  - name: Setup sample gitconfig
    copy: src=file/.gitconfig dest={{ ansible_user_dir }}/.gitconfig

  - name: Copy global gitignore file
    copy: src=file/.gitignore_global dest={{ ansible_user_dir }}/.gitignore_global

  - name: Copy git commit message sample
    copy: src=file/.gitmessage dest={{ ansible_user_dir }}/.gitmessage

  - name: Setup an alias for the loopback adapter
    sudo: yes
    copy:
      src: loopback.alias.plist
      dest: /Library/LaunchDaemons/loopback.alias.plist
    become: yes

  - name: Setup dnsmasq configuration file
    copy:
      src: dnsmasq.conf
      dest: /usr/local/etc/dnsmasq.conf

  - name: Copy dnsmasq startup plist file
    sudo: yes
    copy:
      src: homebrew.mxcl.dnsmasq.plist
      dest: /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
    become: yes

  - name: Setup resolver for .test domains
    lineinfile:
      dest: /etc/resolver/test
      line: "nameserver 127.0.0.1"
      create: yes
    become: yes

  - name: Start dnsmasq on boot
    command: brew services start dnsmasq
